# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: tcp-log
  path.config: "/usr/share/logstash/pipeline/tcp"
#- pipeline.id: file-csv-1
#  path.config: "/usr/share/logstash/pipeline/file/logstash-case-1.conf"
- pipeline.id: file-csv-2
  path.config: "/usr/share/logstash/pipeline/file/logstash-case-1-auto.conf"
  pipeline.workers: 1
