# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "2.0"
services:
  elasticsearch:
    image: docker-elasticsearch:${TAG}
    container_name: docker-elasticsearch_${TAG}
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../cache/es-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  logstash:
    image: docker-logstash:${TAG}
    container_name: docker-logstash_${TAG}
    ports:
      - 5050:5050
      - 9600:9600
    volumes:
      - ../conf/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ../conf/logstash/pipeline:/usr/share/logstash/pipeline
      - ../conf/logstash/logs:/usr/share/logstash/logs
    networks:
      - elastic
    command: ["tail", "-f", "/dev/null"]

  kibana:
    image: docker-kibana:${TAG}
    container_name: docker-kibana_${TAG}
    ports:
      - 5601:5601
    volumes:
      - ../conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

  test:
    image: docker-test:${TAG}
    container_name: docker-test_${TAG}
    volumes:
      - ../test:/shell
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
