# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "2.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: docker-elasticsearch_${TAG}
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    container_name: docker-logstash_${TAG}
    ports:
      - 5050:5050
      - 9600:9600
    volumes:
      - ../conf/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ../conf/logstash/pipeline:/usr/share/logstash/pipeline
      - ../conf/logstash/logs:/usr/share/logstash/logs/input
      - ../cache/logs:/usr/share/logstash/logs/output
    networks:
      - elastic
    command: ["tail", "-f", "/dev/null"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: docker-kibana_${TAG}
    ports:
      - 5601:5601
    networks:
      - elastic

  test:
    image: docker-test:${TAG}
    container_name: docker-test_${TAG}
    volumes:
      - ../test:/shell
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
